server:
  address: localhost
  port: 8080

spring:
  application:
    name: GestioneComanda
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: notifyPrepEvent
      group-id: gestioneCucina
    consumer:
      topic: sendOrderEvent
      group-id: gestioneComanda
